package com.jsf.radiobutton;

import java.io.Serializable;
import java.util.Map;
import java.util.LinkedHashMap;

public class UserBeanRadioButton{

	String favoriteCar1, favoriteCar2, favoriteCar3;

	public String getFavoriteCar1() {
		return favoriteCar1;
	}

	public void setFavoriteCar1(String favoriteCar1) {
		this.favoriteCar1 = favoriteCar1;
	}

	public String getFavoriteCar2() {
		return favoriteCar2;
	}

	public void setFavoriteCar2(String favoriteCar2) {
		this.favoriteCar2 = favoriteCar2;
	}

	public String getFavoriteCar3() {
		return favoriteCar3;
	}

	public void setFavoriteCar3(String favoriteCar3) {
		this.favoriteCar3 = favoriteCar3;
	}

	//generated by Map
	private static Map<String, Object> car2Value;
	static
	{
		car2Value = new LinkedHashMap<String, Object>();

		car2Value.put("BMW 335", "335"); //label, value
		car2Value.put("BMW 316", "316");
		car2Value.put("BMW M3 SMG", "M3 SMG");
	}

	public Map<String, Object> getFavoriteCar2Value()
	{
		return car2Value;
	}

	//generated by Object array
	public static class Car
	{
		public String carLabel;
		public String carValue;

		public Car(String carLabel, String carValue)
		{
			this.carLabel = carLabel;
			this.carValue = carValue;
		}

		public String getCarLabel(){
			return carLabel;
		}

		public String getCarValue(){
			return carValue;
		}

	}

	public Car[] car3List;
	public Car[] getFavoriteCar3Value()
	{
		car3List = new Car[3];

		car3List[0] = new Car("BMW 335", "335");
		car3List[1] = new Car("BMW 316", "316");
		car3List[2] = new Car("BMW M3 SMG", "M3 SMG");

		return car3List;
	}
}